import type { JobOpening } from "@/types/content";

export const jobs: JobOpening[] = [
  {
    id: "executive-sales-assistant-sales",
    title: "Executive Sales / Asst. Sales",
    openings: "2 openings",
    interviewLocation: "H-56, Sector 63, Noida",
    jobLocation: "Noida / Greater Noida (West)",
    experience: "0 to 1.5 years in real estate sales",
    qualifications: "MBA (Marketing)",
    responsibilities: [
      "Interact with channel partners to fulfill demand and expand sales reach.",
      "Develop new clients and maintain existing relationships.",
      "Support periodic sales performance reviews.",
      "Prepare daily activity reports and build new broker and associate relationships.",
    ],
    contactEmail: "priyanka.victoryone@gmail.com",
    contactPhone: "0120-4266606/07/14/28",
  },
  {
    id: "front-desk-officer",
    title: "Front Desk Officer / Manager",
    openings: "1 opening",
    interviewLocation: "H-56, Sector 63, Noida",
    jobLocation: "Noida",
    experience: "1 to 1.5 years in a real estate company",
    qualifications: "UG / Graduate / MBA",
    responsibilities: [
      "Handle visitors, incoming calls, and outgoing calls.",
      "Maintain visitor and call records in Excel.",
      "Manage bills, housekeeping, pantry, and stationery coordination.",
      "Maintain front desk records and communication flow.",
    ],
    contactEmail: "priyanka.victoryone@gmail.com",
    contactPhone: "0120-4266606/07/14/28",
  },
  {
    id: "sr-sales-manager",
    title: "Sr. Sales Manager",
    openings: "1 opening",
    interviewLocation: "H-56, Sector 63, Noida",
    jobLocation: "Noida / Greater Noida (West)",
    experience: "2+ years in a real estate company",
    qualifications: "MBA (Marketing)",
    responsibilities: [
      "Manage channel partner demand generation and client relationships.",
      "Support periodic sales reviews and target achievement.",
      "Track team activity reports and meeting documentation.",
      "Maintain oversight on sales performance and execution discipline.",
    ],
    contactEmail: "priyanka.victoryone@gmail.com",
    contactPhone: "0120-4266606/07/14/28",
  },
  {
    id: "agm-sales",
    title: "AGM - Sales",
    openings: "1 opening",
    interviewLocation: "H-56, Sector 63, Noida",
    jobLocation: "Noida / Greater Noida (West)",
    experience: "4+ years in a real estate company",
    qualifications: "MBA (Marketing)",
    responsibilities: [
      "Assist in development of sales and pricing strategies.",
      "Develop channel partners and handle a team of 6 to 8 members.",
      "Anchor weekly meetings and coordinate with lead providers.",
      "Monitor sales execution, reporting, and target achievement.",
    ],
    contactEmail: "priyanka.victoryone@gmail.com",
    contactPhone: "0120-4266606/07/14/28",
  },
  {
    id: "dgm-sales",
    title: "DGM - Sales",
    openings: "1 opening",
    interviewLocation: "H-56, Sector 63, Noida",
    jobLocation: "Noida / Greater Noida (West)",
    experience: "5+ years in a real estate company",
    qualifications: "MBA (Marketing)",
    responsibilities: [
      "Develop sales and pricing strategies for demand creation.",
      "Build channel partner networks and supervise a 6 to 8 member team.",
      "Review sales performance, reporting, and meeting quality.",
      "Coordinate lead sources and guide execution against targets.",
    ],
    contactEmail: "priyanka.victoryone@gmail.com",
    contactPhone: "0120-4266606/07/14/28",
  },
];
