import type { Project } from "@/types/content";

const currentProjects: Project[] = [
  {
    id: "victoryone-amara",
    slug: "victoryone-amara",
    name: "VictoryOne Amara",
    businessId: "victoryone-group",
    status: "ongoing",
    segment: "residential",
    location: "GH-05 C, Sector-16, Greater Noida (West)",
    overview:
      "VictoryOne Amara is a fully furnished residential project with 2 and 3 BHK apartments, lifestyle amenities, and direct access to location details, construction updates, walkthroughs, and sample-flat visuals.",
    highlights: [
      "Air-conditioners in all bedrooms",
      "Built-in hob and chimney",
      "Wooden wardrobes in all bedrooms",
      "Light and fan in all bedrooms",
      "Choice of flooring",
      "Choice of wall colours",
    ],
    gallery: [
      "/legacy/theme-images/post/amara-3d1.jpg",
      "/legacy/theme-images/post/amara-site-pic1.jpg",
      "/legacy/theme-images/post/amara-site-pic5.jpg",
      "/legacy/theme-images/post/amara-sample-flat-1.jpg",
      "/legacy/theme-images/post/amara-sample-flat-2.jpg",
      "/legacy/theme-images/post/amara-sample-flat-8.jpg",
    ],
    downloads: [
      {
        label: "Amara Brochure",
        href: "/legacy/uploads/2019/02/AMARA-BROUCHURE-19.pdf",
        eventId: "brochure-amara",
      },
      {
        label: "Amara Application Form",
        href: "/legacy/uploads/2018/01/Amara-Application-Form.pdf",
        eventId: "application-amara",
      },
      {
        label: "Amara Price List (Tower A, B and C)",
        href: "/legacy/uploads/2019/12/amara-price-list-25-NOV-2019.pdf",
        eventId: "price-amara-abc",
      },
      {
        label: "Amara Price List (Tower D and E)",
        href: "/legacy/uploads/2018/07/Amara-Price-list-Tower-D-E.pdf",
        eventId: "price-amara-de",
      },
    ],
    isFeatured: true,
    heroImage: "/legacy/theme-images/amara-park-view.jpg",
    thumbnail: "/legacy/theme-images/project-homepg-amara.jpg",
    tags: ["2 BHK", "3 BHK", "Fully furnished", "Greater Noida West"],
    rera: "UPRERAPRJ6187",
    brochureUrl: "/legacy/uploads/2019/02/AMARA-BROUCHURE-19.pdf",
    complianceNotes: [
      "RERA registration is shown in the project details.",
      "Construction updates, map access, walkthrough references, and sample-flat visuals remain part of the project story.",
    ],
  },
  {
    id: "victoryone-central",
    slug: "victoryone-central",
    name: "VictoryOne Central",
    businessId: "victoryone-group",
    status: "ongoing",
    segment: "residential",
    location: "Plot No-02 E, Sector-12 Greater Noida (West)",
    overview:
      "VictoryOne Central is a fully furnished residential project with 2 and 3 BHK apartments, the same core furnished-living feature set highlighted on Amara, and direct access to construction, map, walkthrough, and sample-flat references.",
    highlights: [
      "Air-conditioners in all bedrooms",
      "Built-in hob and chimney",
      "Wooden wardrobes in all bedrooms",
      "Light and fan in all bedrooms",
      "Choice of flooring",
      "Choice of wall colours",
    ],
    gallery: [
      "/legacy/theme-images/victory-one-central-pool-night.jpg",
      "/legacy/theme-images/post/central-3d1.jpg",
      "/legacy/theme-images/post/central-site-layout.jpg",
      "/legacy/theme-images/post/central-sample-flat-1.jpg",
      "/legacy/theme-images/post/central-sample-flat-4.jpg",
      "/legacy/theme-images/post/central-sample-flat-9.jpg",
    ],
    downloads: [
      {
        label: "Central Brochure",
        href: "/legacy/uploads/2019/02/CENTRAL-BROUCHURE-19.pdf",
        eventId: "brochure-central",
      },
      {
        label: "Central Application Form",
        href: "/legacy/uploads/2018/01/central-application-form.pdf",
        eventId: "application-central",
      },
      {
        label: "Central Price List",
        href: "/legacy/uploads/2019/12/central-price-list-26-July-2019.pdf",
        eventId: "price-central",
      },
    ],
    isFeatured: true,
    heroImage: "/legacy/theme-images/victory-one-central-pool-night.jpg",
    thumbnail: "/legacy/theme-images/project-homepg-central.jpg",
    tags: ["2 BHK", "3 BHK", "Fully furnished", "Greater Noida West"],
    rera: "UPRERAPRJ5889",
    brochureUrl: "/legacy/uploads/2019/02/CENTRAL-BROUCHURE-19.pdf",
    complianceNotes: [
      "RERA registration is shown in the project details.",
      "Brochure, application form, and price-list downloads remain available from the project page.",
    ],
  },
  {
    id: "victoryone-amara-commercial",
    slug: "victoryone-amara-commercial",
    name: "VictoryOne Amara Commercial",
    businessId: "victoryone-group",
    status: "ongoing",
    segment: "commercial",
    location: "GH-05 C, Sector-16, Greater Noida (West)",
    overview:
      "VictoryOne Amara Commercial focuses on commercial floor imagery, pricing collateral, and construction update visuals connected to the same Greater Noida West project context.",
    highlights: [
      "Floor galleries remain visible through the current project media set",
      "Construction updates driven by category 6 posts",
      "Commercial enquiries can be sent directly from this project page.",
    ],
    gallery: [
      "/legacy/theme-images/post/amara-spectrum1.jpg",
      "/legacy/theme-images/post/amara-spectrum2.jpg",
      "/legacy/theme-images/post/amara-spectrum3.jpg",
      "/legacy/theme-images/construction-commercial-amara1.jpg",
      "/legacy/theme-images/post/construction-commercial-amara3.jpg",
      "/legacy/theme-images/post/construction-commercial-amara6.jpg",
    ],
    downloads: [
      {
        label: "Amara Commercial Brochure",
        href: "/legacy/uploads/2018/07/Amara-Brouchure.pdf",
        eventId: "brochure-amara-commercial",
      },
    ],
    isFeatured: true,
    heroImage: "/legacy/theme-images/post/amara-commercial1.jpg",
    thumbnail: "/legacy/theme-images/menu-Amara.jpg",
    tags: ["Commercial", "Construction updates", "Greater Noida West"],
    brochureUrl: "/legacy/uploads/2018/07/Amara-Brouchure.pdf",
    complianceNotes: [
      "Commercial construction visuals remain visible alongside the available downloads.",
    ],
  },
  {
    id: "victoryone-central-commercial",
    slug: "victoryone-central-commercial",
    name: "VictoryOne Central Commercial",
    businessId: "victoryone-group",
    status: "ongoing",
    segment: "commercial",
    location: "Plot No-02 E, Sector-12 Greater Noida (West)",
    overview:
      "VictoryOne Central Commercial presents pricing collateral, floor references for ground and first floor, and construction update visuals tied to the same project context.",
    highlights: [
      "Ground floor and first floor references remain available on the page",
      "Construction update imagery remains visible in the commercial gallery",
      "Commercial enquiries can be sent directly from this project page",
    ],
    gallery: [
      "/legacy/theme-images/gf-commercial.jpg",
      "/legacy/theme-images/ff-commercial.jpg",
      "/legacy/theme-images/construction-commercial-central1.jpg",
      "/legacy/theme-images/post/construction-commercial-centra2.jpg",
      "/legacy/theme-images/post/construction-commercial-centra3.jpg",
      "/legacy/theme-images/post/construction-commercial-centra4.jpg",
    ],
    downloads: [
      {
        label: "Central Commercial Price List",
        href: "/legacy/uploads/2019/12/central-price-list-26-July-2019.pdf",
        eventId: "price-central-commercial",
      },
      {
        label: "Central Brochure",
        href: "/legacy/uploads/2019/02/CENTRAL-BROUCHURE-19.pdf",
        eventId: "brochure-central-commercial",
      },
    ],
    isFeatured: true,
    heroImage: "/legacy/theme-images/post/central-3d4.jpg",
    thumbnail: "/legacy/theme-images/menu-Central.jpg",
    tags: ["Commercial", "Floor plans", "Greater Noida West"],
    brochureUrl: "/legacy/uploads/2019/02/CENTRAL-BROUCHURE-19.pdf",
    complianceNotes: [
      "Commercial pricing material and construction visuals remain available for review.",
    ],
  },
];

const pastProjectSeed = [
  ["container-corporation-of-india-dadri-2010", "Container Corporation of India", "International Containers Depot, Dadri, UP, 2010", "20 Acres", "residential", "container-corporation-of-india-dadri-up-20acres.jpg"],
  ["mitsui-corp-yakult-danone-2009", "Mitsui Corp", "Yakult Danone, Sonepat, 2009", "20.0 L Sq. Ft.", "residential", "mitsui-corp.jpg"],
  ["container-corporation-of-india-dadri-2009", "Container Corporation of India", "International Containers Depot, Dadri, UP, 2009", "10 Acres", "residential", "container-corporation-of-india-dadri-up.jpg"],
  ["container-corporation-of-india-tuglakabad-2009", "Container Corporation of India", "International Containers Depot, Tuglakabad, Delhi, 2009", "5.0 Acres", "residential", "container-corporation-of-india-tuglakabad-delhi.jpg"],
  ["nokia-siemens-network-2009", "Nokia Siemens Network", "Development of SEZ, Chennai, 2009", "100 Acres", "residential", "nokia-siemens-network.jpg"],
  ["areva-kalpakkam-2009", "Areva", "Nuclear Power Corporation of India, Kalpakkam (Chennai), 2009", "1.0 L Sq. Ft.", "residential", "areva.jpg"],
  ["victory-crossroads-2008", "Victory Crossroads", "Sector 143 Noida, 2008", "Delivered", "residential", "victory-crossroads.jpg"],
  ["reliance-energy-66kv-2007", "66KV Sub Station for Reliance Energy Ltd", "Pappankala, Delhi, 2007", "1.5 L Sq. Ft.", "residential", "66-kv-sub-station-for-reliance-energy-ltd.jpg"],
  ["mitsui-morrirokknut-2007", "Mitsui Corp-Morrirokknut", "Noida (Unit of Honda), 2007", "7.0 L Sq. Ft.", "industrial", "mitsui-corp-morrirokknut.jpg"],
  ["reliance-energy-33kv-2006", "33KV Sub Station for Reliance Energy Ltd", "Jhilmil, Delhi, 2006", "1.0 L Sq. Ft.", "industrial", "33-kv-sub-station-for-reliance-energy-ltd.jpg"],
  ["mitsui-nhk-2005", "Mitsui Corp. NHK", "Manesar (Unit Of Honda), 2005", "8.0 L Sq. Ft.", "industrial", "mitsui-corp-nhk.jpg"],
  ["bilga-hospital-trust-2005", "Bilga Hospital Trust", "Hospital Funded by NRI’s, Ludhiana, 2005", "3.0 L Sq. Ft.", "industrial", "bilga-hospital-trust.jpg"],
  ["mitsui-h-one-2005", "Mitsui Corp H-One", "Greater Noida (Unit of Honda), 2005", "10.0 L Sq. Ft.", "industrial", "mitsui-corp-h-one.jpg"],
  ["urjavihar-cghs-2003", "UrjaVihar CGHS", "Faridabad, 2003", "2.5 L Sq. Ft.", "industrial", "urjavihar-cghs.jpg"],
  ["lic-housing-2003", "Housing of LIC Policy", "Callicut, Kerela, 2003", "5.0 L Sq. Ft.", "industrial", "LIC-housing-of-LIC-policy.jpg"],
  ["army-welfare-housing-2002", "Army Welfare Housing Organisation", "Orrisa, 2002", "6.0 L Sq. Ft.", "health-care", "army-welfare-housing-organisation.jpg"],
  ["surya-cghs-2002", "Surya CGHS", "Delhi, 2002", "4.5 L Sq. Ft.", "health-care", "surya-cghs.jpg"],
  ["progressive-cghs-2001", "Progressive CGHS", "Delhi, 2001", "6.0 L Sq. Ft.", "energy", "progressive-cghs.jpg"],
  ["delhi-cantoment-board-2001", "Delhi Cantoment Board", "Cantoment Hospital, Delhi, 2001", "4.0 L Sq. Ft.", "energy", "delhi-cantoment-board.jpg"],
  ["huda-2000", "HUDA", "Mini Secretariat, Karnal, 2000", "3.0 L Sq. Ft.", "infrastructure", "huda.jpg"],
  ["milan-vihar-1999", "Milan Vihar", "Delhi, 1999", "8.0 L Sq. Ft.", "nuclear-power", "milan-vihar.jpg"],
  ["gyan-shakti-cghs-1998", "Gyan Shakti CGHS", "Delhi, 1998", "5.0 L Sq. Ft.", "government", "gyan-shakti-cghs.jpg"],
] as const;

const pastProjects: Project[] = pastProjectSeed.map(
  ([slug, name, location, sizeLabel, segment, image]): Project => ({
    id: slug,
    slug,
    name,
    businessId: "victoryone-group",
    status: "completed",
    segment,
    location,
    overview: `${name} is included in VictoryOne's delivered portfolio with location and approximate size details.`,
    highlights: [location, `Approx. Size: ${sizeLabel}`],
    gallery: [`/legacy/theme-images/post/${image}`],
    downloads: [],
    isFeatured: false,
    heroImage: `/legacy/theme-images/post/${image}`,
    thumbnail: `/legacy/theme-images/post/${image}`,
    tags: ["Delivered portfolio", segment, sizeLabel],
    sizeLabel,
  }),
);

export const projects: Project[] = [...currentProjects, ...pastProjects];

